ALTER TABLE users
  ADD COLUMN IF NOT EXISTS place_of_birth VARCHAR(100),
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS birth_date VARCHAR(10),
  ADD COLUMN IF NOT EXISTS faculty VARCHAR(100),
  ADD COLUMN IF NOT EXISTS semester INTEGER;
